//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::Type;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cyberware")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub humanity_loss: i32,
    pub r#type: Option<Type>,
    pub is_foundational: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub effect: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::gear::Entity",
        from = "Column::Id",
        to = "super::gear::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Gear,
}

impl Related<super::gear::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gear.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
