//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "type")]
pub enum Type {
    #[sea_orm(string_value = "very_light_melee")]
    VeryLightMelee,
    #[sea_orm(string_value = "light_melee")]
    LightMelee,
    #[sea_orm(string_value = "medium_melee")]
    MediumMelee,
    #[sea_orm(string_value = "heavy_melee")]
    HeavyMelee,
    #[sea_orm(string_value = "light_pistol")]
    LightPistol,
    #[sea_orm(string_value = "medium_pistol")]
    MediumPistol,
    #[sea_orm(string_value = "heavy_pistol")]
    HeavyPistol,
    #[sea_orm(string_value = "very_heavy_pistol")]
    VeryHeavyPistol,
    #[sea_orm(string_value = "smg")]
    Smg,
    #[sea_orm(string_value = "heavy_smg")]
    HeavySmg,
    #[sea_orm(string_value = "shotgun")]
    Shotgun,
    #[sea_orm(string_value = "assault_rifle")]
    AssaultRifle,
    #[sea_orm(string_value = "sniper_rifle")]
    SniperRifle,
    #[sea_orm(string_value = "grenade_launcher")]
    GrenadeLauncher,
    #[sea_orm(string_value = "rocket_launcher")]
    RocketLauncher,
}
