//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "group")]
pub enum Group {
    #[sea_orm(string_value = "mental")]
    Mental,
    #[sea_orm(string_value = "combat")]
    Combat,
    #[sea_orm(string_value = "fortune")]
    Fortune,
    #[sea_orm(string_value = "physical")]
    Physical,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "install")]
pub enum Install {
    #[sea_orm(string_value = "mall")]
    Mall,
    #[sea_orm(string_value = "clinic")]
    Clinic,
    #[sea_orm(string_value = "hospital")]
    Hospital,
}
