//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "skill")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
    pub derived_stat_id: i32,
    pub source_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::source::Entity",
        from = "Column::SourceId",
        to = "super::source::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Source,
    #[sea_orm(
        belongs_to = "super::stat::Entity",
        from = "Column::DerivedStatId",
        to = "super::stat::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Stat,
}

impl Related<super::source::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Source.def()
    }
}

impl Related<super::stat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stat.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::source::Entity")]
    Source,
    #[sea_orm(entity = "super::stat::Entity")]
    Stat,
}
